---
- name: Set MSFT repo url
  ansible.builtin.set_fact:
    msft_repo: "{{ item.url }}"
  when:
    - ansible_lsb.codename == item.codename
  with_items:
    - codename: lunar
      url: https://packages.microsoft.com/ubuntu/23.04/prod lunar
    - codename: kinetic
      url: https://packages.microsoft.com/ubuntu/22.10/prod kinetic
    - codename: jammy
      url: https://packages.microsoft.com/ubuntu/22.04/prod jammy
    - codename: impish
      url: https://packages.microsoft.com/ubuntu/21.10/prod impish
    - codename: hirsute
      url: https://packages.microsoft.com/ubuntu/21.04/prod hirsute
    - codename: groovy
      url: https://packages.microsoft.com/ubuntu/20.10/prod groovy
    - codename: focal
      url: https://packages.microsoft.com/ubuntu/20.04/prod focal
    - codename: eoan
      url: https://packages.microsoft.com/ubuntu/19.10/prod eoan
    - codename: disco
      url: https://packages.microsoft.com/ubuntu/19.04/prod disco
    - codename: cosmic
      url: https://packages.microsoft.com/ubuntu/18.10/prod cosmic
    - codename: bionic
      url: https://packages.microsoft.com/ubuntu/18.04/prod bionic
    - codename: artful
      url: https://packages.microsoft.com/ubuntu/17.10/prod artful
    - codename: zesty
      url: https://packages.microsoft.com/ubuntu/17.04/prod zesty
    - codename: yakkety
      url: https://packages.microsoft.com/ubuntu/16.10/prod yakkety
    - codename: xenial
      url: https://packages.microsoft.com/ubuntu/16.04/prod xenial
    - codename: wily
      url: https://packages.microsoft.com/ubuntu/15.10/prod wily
    - codename: trusty
      url: https://packages.microsoft.com/ubuntu/14.04/prod trusty
    - codename: jessie
      url: https://packages.microsoft.com/repos/microsoft-debian-jessie-prod jessie
    - codename: stretch
      url: https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch
    - codename: buster
      url: https://packages.microsoft.com/repos/microsoft-debian-buster-prod buster
    - codename: bullseye
      url: https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye
    - codename: bookworm
      url: https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm

- name: Allow release-info to change for APT repositories
  ansible.builtin.command: apt-get update -y --allow-releaseinfo-change

- name: Install Pre-Requistes
  ansible.builtin.apt:
    name: ['gnupg', 'gawk', 'apt-transport-https']
    state: present

- name: Install MSFT GPG key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add MSFT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] {{ msft_repo }} main"
    filename: microsoft
    state: present
    update_cache: yes
