---

- name: Add MSFT repo fro RHEL
  yum_repository:
    name: packages-microsoft-com-prod
    description: packages-microsoft-com-prod
    file: microsoft-prod
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    # baseurl: https://packages.microsoft.com/rhel/{{ansible_distribution_major_version}}/prod/
    baseurl: https://packages.microsoft.com/rhel/7/prod/
    gpgcheck: yes
    enabled: yes
    sslverify: yes

- name: Change mirror.centos.org to vault.centos.org for CentOS 8, as it is defined EOL (step 1)
  ansible.builtin.shell: sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8' and ansible_distribution_release != 'Stream'

- name: Change mirror.centos.org to vault.centos.org for CentOS 8, as it is defined EOL (step 2)
  ansible.builtin.shell: sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8' and ansible_distribution_release != 'Stream'

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "libicu"
    - "libunwind"
  when: ansible_distribution_release != 'Stream'
