---

- name: Add MSFT repo fro RHEL
  yum_repository:
    name: packages-microsoft-com-prod
    description: packages-microsoft-com-prod
    file: microsoft-prod
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    #baseurl: https://packages.microsoft.com/rhel/{{ansible_distribution_major_version}}/prod/
    baseurl: https://packages.microsoft.com/rhel/7/prod/
    gpgcheck: yes
    enabled: yes
    sslverify: yes

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "libicu"
    - "libunwind"

